title: Fernando Malta — Portfolio
description: Creative leadership • Visual narratives • Brand identity
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-seo-tag

navbar-links:
  Home: /
  Raia Drogasil: /clients/raia-drogasil.html
  Heineken: /clients/heineken-brasil.html
  Itaú: /clients/itau.html
  Coca-Cola: /clients/coca-cola.html
  Natura: /clients/natura.html